name: Build and deploy frontend

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - 'frontend/**'
jobs:

  build:

    runs-on: ubuntu-latest
    env:
      imageRepository: 'frontend'
      containerRegistry: 'ashgloboticket.azurecr.io'
      dockerfilePath: 'frontend/Dockerfile'
      deploymentFile: 'frontend.yaml'
      namespace: 'globoticket'

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2 
      with:
        registry: ${{ env.containerRegistry }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_TOKEN }}
    
    - name: Build an image from Dockerfile
      run: |
        docker build -t ${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}} -f ${{env.dockerfilePath}} ${{github.workspace}}
        
 
        
  
    - name: push image to ACR
      run: |
        docker push ${{env.containerRegistry}}/${{env.imageRepository}}:${{github.run_number}}

    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.0
      with:
        files: ${{github.workspace}}/demos/remote-k8s/deployment-automation/${{env.deploymentFile}}
      env: 
        Build.BuildId: ${{github.run_number}}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: deployfile
        path: https://github.com/Dexterslab/asp-dot-net-6-kubernetes/blob/main/demos/remote-K8s/deployment-automation/frontend.yaml
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: deployfile
          
 
    - uses: Azure/k8s-deploy@v4
      with:
        namespace: 'globoticket'
        manifests: |
            ./${{env.deploymentFile}}
